name: 'Post to LinkedIn'
description: 'Post content to LinkedIn using the LinkedIn API'
author: 'Gerald Nguyen'
branding:
  icon: 'linkedin'
  color: 'blue'

inputs:
  access-token:
    description: 'LinkedIn Access Token'
    required: true
  author-id:
    description: 'LinkedIn Author ID (person or organization URN)'
    required: true
  content:
    description: 'Content to post to LinkedIn'
    required: true
  media-files:
    description: 'Comma-separated list of media file paths to attach (optional)'
    required: false
  link:
    description: 'Link to attach to the post (optional)'
    required: false
  log-level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR)'
    required: false
    default: 'INFO'
  content-json:
    description: 'JSON API URL and path for dynamic content templating (e.g. https://example.com/data.json | items[RANDOM])'
    required: false
  time-zone:
    description: 'Time zone for date/time placeholders (e.g. UTC, UTC+7)'
    required: false
  dry-run:
    description: 'Dry run mode. If true, the content will be printed but not posted.'
    required: false
    default: 'false'

outputs:
  post-id:
    description: 'ID of the created post'
  post-url:
    description: 'URL of the created post'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
    
    - name: Post to LinkedIn
      shell: bash
      env:
        LINKEDIN_ACCESS_TOKEN: ${{ inputs.access-token }}
        LINKEDIN_AUTHOR_ID: ${{ inputs.author-id }}
        POST_CONTENT: ${{ inputs.content }}
        MEDIA_FILES: ${{ inputs.media-files }}
        POST_LINK: ${{ inputs.link }}
        LOG_LEVEL: ${{ inputs.log-level }}
        CONTENT_JSON: ${{ inputs.content-json }}
        TIME_ZONE: ${{ inputs.time-zone }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        python ${{ github.action_path }}/post_to_linkedin.py
