name: 'Post to Facebook Page'
description: 'Post content to a Facebook Page using the Facebook Graph API'
author: 'Gerald Nguyen'
branding:
  icon: 'facebook'
  color: 'blue'

inputs:
  access-token:
    description: 'Facebook Page Access Token'
    required: true
  page-id:
    description: 'Facebook Page ID (required for posts, not required for comments)'
    required: false
  content:
    description: 'Content to post to Facebook Page or comment text'
    required: true
  fb-post-id:
    description: 'Facebook Post ID to comment on (if provided, will post as comment instead of new post)'
    required: false
  media-files:
    description: 'Comma-separated list of media file paths to attach (optional, for posts only - comments only support URLs in text)'
    required: false
  link:
    description: 'Link to attach to the post or include in comment text (optional)'
    required: false
  log-level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR)'
    required: false
    default: 'INFO'
  content-json:
    description: 'JSON API URL and path for dynamic content templating (e.g. https://example.com/data.json | items[RANDOM])'
    required: false
  time-zone:
    description: 'Time zone for date/time placeholders (e.g. UTC, UTC+7)'
    required: false
  dry-run:
    description: 'Dry run mode. If true, the content will be printed but not posted.'
    required: false
    default: 'false'
  scheduled-publish-time:
    description: 'Schedule post for future publication (posts only, not supported for comments). Supports ISO 8601 (e.g., "2024-12-31T23:59:59Z") or offset format (e.g., "+1d", "+2h", "+30m")'
    required: false

outputs:
  post-id:
    description: 'ID of the created post (if posting)'
  post-url:
    description: 'URL of the created post (if posting)'
  comment-id:
    description: 'ID of the created comment (if commenting)'
  comment-url:
    description: 'URL of the created comment (if commenting)'
  scheduled-time:
    description: 'Scheduled publish time (if scheduling was used for posts)'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
    
    - name: Post to Facebook Page
      shell: bash
      env:
        FB_ACCESS_TOKEN: ${{ inputs.access-token }}
        FB_PAGE_ID: ${{ inputs.page-id }}
        POST_CONTENT: ${{ inputs.content }}
        FB_POST_ID: ${{ inputs.fb-post-id }}
        MEDIA_FILES: ${{ inputs.media-files }}
        POST_LINK: ${{ inputs.link }}
        LOG_LEVEL: ${{ inputs.log-level }}
        CONTENT_JSON: ${{ inputs.content-json }}
        TIME_ZONE: ${{ inputs.time-zone }}
        DRY_RUN: ${{ inputs.dry-run }}
        SCHEDULED_PUBLISH_TIME: ${{ inputs.scheduled-publish-time }}
      run: |
        python ${{ github.action_path }}/post_to_facebook.py