name: 'Social Media Posting Example'

on:
  # Trigger manually for testing
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to post'
        required: true
        default: 'Hello from GitHub Actions! 🚀'
      include_link:
        description: 'Include repository link'
        type: boolean
        required: false
        default: false

  # Trigger on releases
  release:
    types: [published]

jobs:
  post-to-social-media:
    runs-on: ubuntu-latest
    name: Post to Social Media
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Post to X (Twitter)
      - name: Post to X
        uses: ./post-to-x
        with:
          api-key: ${{ secrets.X_API_KEY }}
          api-secret: ${{ secrets.X_API_SECRET }}
          access-token: ${{ secrets.X_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          content: |
            ${{ inputs.message || 'New release published!' }} 
            ${{ inputs.include_link == 'true' && format('🔗 {0}', github.event.repository.html_url) || '' }}
          log-level: 'INFO'
      
      # Post to Facebook Page
      - name: Post to Facebook Page
        uses: ./post-to-facebook
        with:
          access-token: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          page-id: ${{ secrets.FB_PAGE_ID }}
          content: |
            ${{ inputs.message || 'We have a new release available!' }}
            
            Check out our repository for more details.
          link: ${{ inputs.include_link == 'true' && github.event.repository.html_url || '' }}
          log-level: 'INFO'
      
      # Post to Threads
      - name: Post to Threads
        uses: ./post-to-threads
        with:
          access-token: ${{ secrets.THREADS_ACCESS_TOKEN }}
          user-id: ${{ secrets.THREADS_USER_ID }}
          content: |
            ${{ inputs.message || 'New release! 🎉' }}
            ${{ inputs.include_link == 'true' && format('Check it out: {0}', github.event.repository.html_url) || '' }}
          log-level: 'INFO'
      
      # Note: Instagram action not included in this example as it requires
      # a publicly accessible media URL. Uncomment and configure if needed:
      #
      # - name: Post to Instagram
      #   uses: ./post-to-instagram
      #   with:
      #     access-token: ${{ secrets.IG_ACCESS_TOKEN }}
      #     user-id: ${{ secrets.IG_USER_ID }}
      #     content: |
      #       ${{ inputs.message || 'New release!' }} 📱✨
      #       
      #       #github #opensource #release
      #     media-file: 'https://your-cdn.com/release-image.jpg'
      #     log-level: 'INFO'