name: 'Tellstory Social Media Posting'

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to post'
        required: true
        default: 'Hello from Tellstory!'
      include_link:
        description: 'Include repository link'
        type: boolean
        required: false
        default: false

jobs:
  post-to-x:
    name: Post to X
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post to X
        uses: geraldnguyen/social-media-posters/copilot/fix-34fd7fc5-b084-49a1-8f22-ebdb9d6a477c/post-to-x
        with:
          api-key: ${{ secrets.X_API_KEY }}
          api-secret: ${{ secrets.X_API_SECRET }}
          access-token: ${{ secrets.X_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          content: |
            ${{ inputs.message }}
            ${{ inputs.include_link == 'true' && format('🔗 {0}', github.event.repository.html_url) || '' }}
          log-level: 'INFO'

  post-to-facebook:
    name: Post to Facebook Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post to Facebook Page
        uses: geraldnguyen/social-media-posters/copilot/fix-34fd7fc5-b084-49a1-8f22-ebdb9d6a477c/post-to-facebook
        with:
          access-token: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          page-id: ${{ secrets.FB_PAGE_ID }}
          content: |
            ${{ inputs.message }}
            ${{ inputs.include_link == 'true' && format('🔗 {0}', github.event.repository.html_url) || '' }}
          log-level: 'INFO'

  post-to-instagram:
    name: Post to Instagram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post to Instagram
        uses: geraldnguyen/social-media-posters/copilot/fix-34fd7fc5-b084-49a1-8f22-ebdb9d6a477c/post-to-instagram
        with:
          access-token: ${{ secrets.IG_ACCESS_TOKEN }}
          user-id: ${{ secrets.IG_USER_ID }}
          content: |
            ${{ inputs.message }}
            ${{ inputs.include_link == 'true' && format('🔗 {0}', github.event.repository.html_url) || '' }}
          # media-file: 'https://your-cdn.com/release-image.jpg' # Uncomment and set if needed
          log-level: 'INFO'

  post-to-threads:
    name: Post to Threads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post to Threads
        uses: geraldnguyen/social-media-posters/copilot/fix-34fd7fc5-b084-49a1-8f22-ebdb9d6a477c/post-to-threads
        with:
          access-token: ${{ secrets.THREADS_ACCESS_TOKEN }}
          user-id: ${{ secrets.THREADS_USER_ID }}
          content: |
            ${{ inputs.message }}
            ${{ inputs.include_link == 'true' && format('🔗 {0}', github.event.repository.html_url) || '' }}
          log-level: 'INFO'
